#Write a program to display a T pattern 
print("===============================")
print("               ||         ")
print("               ||         ")
print("               ||         ")
print("               ||         ")
print("               ||         ")
print("               ||         ")
print("               ||         ")
print("               ||         ")
print("               ||         ")