print("------------------------------------------------------------------------")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                     _____                                            |")
print("|                    |____                                             |")
print("|                    _____|AFARICOM                                    |")
print("|                            Twaweza                                   |")
print("|                                                                      |")
print("|                                                                      |")
print("|                   .Simple .Transparent .Honest                       |")
print("|                            FOR YOU                                   |")
print("|                                                                      |")
print("|                                                                      |")
print("|                            EST.1997.                                 |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("|                                                                      |")
print("------------------------------------------------------------------------")